### PR TITLE
Improve handling of potential names from JSON files

### LINKED ISSUE #249: ValueError when loading potentials from different iterations.
Looping through iterations and trying to load a potential raises: `ValueError: Potential name already used`. 

The minimum reproducer for this is having two directories `0` & `1` each with `pair_potential.json` in them. Then running: 

```
import relentless

for i in range(0, 2):
       spline = relentless.model.potential.PairSpline.from_file("{}/pair_potential.json".format(i))
```    
 The traceback is: 
 
```
> Traceback (most recent call last):
  File "load-potential.py", line 4, in <module>
    spline = relentless.model.potential.PairSpline.from_file("{}/pair_potential.0.json".format(i))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "relentless/model/potential/potential.py", line 220, in from_file
    return cls.from_json(data)
           ^^^^^^^^^^^^^^^^^^^
  File "relentless/model/potential/pair.py", line 876, in from_json
    u = super().from_json(data)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "relentless/model/potential/potential.py", line 194, in from_json
    u = cls(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^
  File "relentless/model/potential/pair.py", line 872, in __init__
    super().__init__(types=types, params=params, name=name)
  File "relentless/model/potential/pair.py", line 187, in __init__
    super().__init__(types, params, PairParameters, name)
  File "relentless/model/potential/potential.py", line 145, in __init__
    raise ValueError("Potential name already used")
ValueError: Potential name already used
```

### PR DESCRIPTION
**Pull request by mphoward**
This PR adds a `name` option for loading potentials from file with multiple options (override, keep, discard, and default). The default mode preserves the current behavior, but it now discards autogenerated names. We have never guaranteed that an autogenerated name is meaningful to the user, so I think it is OK that this behavior changes slightly.

Fixes #249

### CODE REVIEW

**Comment by mphoward** [comment]
@clpetix I think this will fix the issue in your test script!

**Comment by mphoward** [comment]
I rebased, so this one should be ready to look at now

**Comment by clpetix** [comment]
@mphoward I think the `PairSpline` class needs the name argument added here: 

https://github.com/mphowardlab/relentless/blob/2abcbfc220bc56dbe187c83f5823976c39bd7df4/src/relentless/model/potential/pair.py#L875

**Comment by mphoward** [comment]
> I think the `PairSpline` class needs the name argument added here:

Yes, definitely! Are there any other derived classes overriding `from_json`?

**Comment by clpetix** [comment]
> > I think the `PairSpline` class needs the name argument added here:
> 
> Yes, definitely! Are there any other derived classes overriding `from_json`?

Nope, looks like it is just `PairSpline`!

**Comment by mphoward** [comment]
> I think the `PairSpline` class needs the name argument added here:

This should be fixed.

**Review by clpetix — APPROVED** [review]
Looks good to me! Thanks!

**Pull request merged**
