### PR TITLE
Refactor interpolators and splines

### PR DESCRIPTION
**Pull request by mphoward**
This PR refactors `Interpolator` and `PairSpline` to give future flexibility in defining the spline potential. For example, it would now be possible to implement B splines in the pair potential rather than Akima splines. This was not previously possible.

It also modifies the way the knot positions are stored so that they are now differences. This would allow these variables to be optimized in future.

One question is if we should rename "mode" to "style" or something like that. We could also separate them into a "mode" (which is value or diff) AND a "style" / "basis" (which is akima, bspline, etc.). That way we would not need to use the "-" that I currently chose. Ex:
```
mode="diff", style="akima"
```
vs.
```
mode="akima-diff"
```

@clpetix what do you think?

### CODE REVIEW

**Comment by clpetix** [comment]
> This PR refactors `Interpolator` and `PairSpline` to give future flexibility in defining the spline potential. For example, it would now be possible to implement B splines in the pair potential rather than Akima splines. This was not previously possible.
> 
> One question is if we should rename "mode" to "style" or something like that. We could also separate them into a "mode" (which is value or diff) AND a "style" / "basis" (which is akima, bspline, etc.). That way we would not need to use the "-" that I currently chose. Ex:
> 
> ```
> mode="diff", style="akima"
> ```
> 
> vs.
> 
> ```
> mode="akima-diff"
> ```
> 
> @clpetix what do you think?

I like the mode & style being separate arguments; that method seems more logical to me!

**Comment by mphoward** [comment]
OK! Then what we will do for now is revert to `mode` for `value` vs. `diff`, and we will internally store the `style="akima"` in a variable. If we decide we want to support B splines, we can then come back and expose the `style` parameter publicly.

**Comment by mphoward** [comment]
This should be ready now. I reverted the changes to `mode` so that it is just `value` or `diff`. I decided it didn't make sense to introduce the `style` variable now if we are not going to do anything with it, but I think this is a clean way to add the option later if we decide we want to support other types of splines.

**Review by clpetix — APPROVED** [review]
This all looks good to me!

**Pull request merged**
